project:
  type: default

format:
  html:
    theme: cosmo
    css: ../styles.css
    toc: true
    toc-depth: 3
    number-sections: true
    html-math-method: katex
    code-copy: true
    code-fold: true
    code-overflow: wrap
    fig-cap-location: bottom

execute:
  eval: true
  warning: false
  message: false
  freeze: false
